export interface TickerInfo {
  nome: string
  setor: string
}

export const TICKERS_INFO: Record<string, TickerInfo> = {
  ABEV3: { nome: 'Ambev S.A.', setor: 'Consumo Não Cíclico' },
  PETR4: { nome: 'Petróleo Brasileiro S.A.', setor: 'Petróleo, Gás e Biocombustíveis' },
  VALE3: { nome: 'Vale S.A.', setor: 'Materiais Básicos' },
  ITUB4: { nome: 'Itaú Unibanco Holding S.A.', setor: 'Financeiro e Outros' },
  BBAS3: { nome: 'Banco do Brasil S.A.', setor: 'Financeiro e Outros' },
  WEGE3: { nome: 'WEG S.A.', setor: 'Bens Industriais' },
  BBSE3: { nome: 'BB Seguridade Participações S.A.', setor: 'Financeiro e Outros' },
  VULC3: { nome: 'Vulcabras S.A.', setor: 'Consumo Cíclico' },
  AZZA3: { nome: 'Azzas 2154 S.A.', setor: 'Consumo Cíclico' },
  CYRE3: { nome: 'Cyrela Brazil Realty S.A.', setor: 'Real Estate' },
  PSSA3: { nome: 'Porto Seguro S.A.', setor: 'Financeiro e Outros' },
  B3SA3: { nome: 'B3 S.A. — Brasil, Bolsa, Balcão', setor: 'Financeiro e Outros' },
  CMIG4: { nome: 'Companhia Energética de Minas Gerais', setor: 'Utilidade Pública' },
  CMIG3: { nome: 'Companhia Energética de Minas Gerais', setor: 'Utilidade Pública' },
  RANI3: { nome: 'Irani Papel e Embalagem S.A.', setor: 'Consumo Cíclico' },
  RECV3: { nome: 'Petrorreconcavo S.A.', setor: 'Petróleo, Gás e Biocombustíveis' },
  SAPR3: { nome: 'Companhia de Saneamento do Paraná', setor: 'Utilidade Pública' },
  SAPR4: { nome: 'Companhia de Saneamento do Paraná', setor: 'Utilidade Pública' },
  LOGG3: { nome: 'LOG Commercial Properties e Participações S.A.', setor: 'Real Estate' },
  ABCB4: { nome: 'Banco ABC Brasil S.A.', setor: 'Financeiro e Outros' },
  BBDC4: { nome: 'Banco Bradesco S.A.', setor: 'Financeiro e Outros' },
  BBDC3: { nome: 'Banco Bradesco S.A.', setor: 'Financeiro e Outros' },
  ITSA4: { nome: 'Itaúsa S.A.', setor: 'Financeiro e Outros' },
  ITSA3: { nome: 'Itaúsa S.A.', setor: 'Financeiro e Outros' },
  SOJA3: { nome: 'Boa Safra Sementes S.A.', setor: 'Consumo Não Cíclico' },
  GRND3: { nome: 'Grendene S.A.', setor: 'Consumo Cíclico' },
  TEND3: { nome: 'Construtora Tenda S.A.', setor: 'Real Estate' },
  LAVV3: { nome: 'Lavvi Empreendimentos Imobiliários S.A.', setor: 'Real Estate' },
  BLAU3: { nome: 'Blau Farmacêutica S.A.', setor: 'Saúde' },
  JHSF3: { nome: 'JHSF Participações S.A.', setor: 'Real Estate' },
  ENGI11: { nome: 'Energisa S.A.', setor: 'Utilidade Pública' },
  BRAV3: { nome: 'Brava Energia S.A.', setor: 'Petróleo, Gás e Biocombustíveis' },
  MYPK3: { nome: 'Iochpe-Maxion S.A.', setor: 'Bens Industriais' },
  ROMI3: { nome: 'Indústrias Romi S.A.', setor: 'Bens Industriais' },
  VLID3: { nome: 'Valid Soluções S.A.', setor: 'Tecnologia da Informação' },
  LEVE3: { nome: 'Mahle Metal Leve S.A.', setor: 'Bens Industriais' },
  SBSP3: { nome: 'Cia. de Saneamento Básico do Estado de São Paulo — Sabesp', setor: 'Utilidade Pública' },
  COGN3: { nome: 'Cogna Educação S.A.', setor: 'Consumo Cíclico' },
  USIM3: { nome: 'Usinas Siderúrgicas de Minas Gerais S.A.', setor: 'Materiais Básicos' },
  USIM5: { nome: 'Usinas Siderúrgicas de Minas Gerais S.A.', setor: 'Materiais Básicos' },
  PRIO3: { nome: 'PRIO S.A.', setor: 'Petróleo, Gás e Biocombustíveis' },
  AXIA5: { nome: 'Âxia Energia S.A.', setor: 'Utilidade Pública' },
  BRAP3: { nome: 'Bradespar S.A.', setor: 'Financeiro e Outros' },
  BRAP4: { nome: 'Bradespar S.A.', setor: 'Financeiro e Outros' },
  POMO3: { nome: 'Marcopolo S.A.', setor: 'Bens Industriais' },
  POMO4: { nome: 'Marcopolo S.A.', setor: 'Bens Industriais' },
  IRBR3: { nome: 'IRB-Brasil Resseguros S.A.', setor: 'Financeiro e Outros' },
  TRIS3: { nome: 'Trisul S.A.', setor: 'Real Estate' },
  SUZB3: { nome: 'Suzano S.A.', setor: 'Materiais Básicos' },
  KLBN11: { nome: 'Klabin S.A.', setor: 'Materiais Básicos' },
  EGIE3: { nome: 'Engie Brasil Energia S.A.', setor: 'Utilidade Pública' },
  TAEE11: { nome: 'Transmissora Aliança de Energia Elétrica S.A.', setor: 'Utilidade Pública' },
  CPFE3: { nome: 'CPFL Energia S.A.', setor: 'Utilidade Pública' },
  CSAN3: { nome: 'Cosan S.A.', setor: 'Petróleo, Gás e Biocombustíveis' },
}

export const TICKERS_LIST = Object.keys(TICKERS_INFO)

export const SETOR_MAP: Record<string, string> = {
  'Basic Materials':        'Materiais Básicos',
  'Communication Services': 'Comunicação',
  'Consumer Cyclical':      'Consumo Cíclico',
  'Consumer Defensive':     'Consumo Não Cíclico',
  'Energy':                 'Energia',
  'Financial Services':     'Financeiro e Outros',
  'Healthcare':             'Saúde',
  'Industrials':            'Bens Industriais',
  'Petróleo':               'Petróleo, Gás e Biocombustíveis',
  'Real Estate':            'Real Estate',
  'Technology':             'Tecnologia da Informação',
  'Utilities':              'Utilidade Pública',
}

export const SETORES = [
  'Todos',
  'Financeiro e Outros',
  'Petróleo, Gás e Biocombustíveis',
  'Materiais Básicos',
  'Consumo Cíclico',
  'Consumo Não Cíclico',
  'Utilidade Pública',
  'Real Estate',
  'Saúde',
  'Bens Industriais',
  'Tecnologia da Informação',
  'Comunicação',
  'Energia',
]
